# Generated by Django 6.0.2 on 2026-02-22 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0003_color_item_colors'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='hhex_code',
            field=models.CharField(default='#000000', max_length=7),
        ),
    ]
