# Generated by Django 6.0.2 on 2026-02-22 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0004_color_hhex_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='color',
            old_name='hhex_code',
            new_name='hex_code',
        ),
    ]
